rights:
  need_admin: [ 
                'admin',
                'commande-utile',
                'registration-checker',
                'registration-handler' 
              ]
  need_email: [ 
                'admin',
                'commande-utile',
                'registration-checker',
                'registration-handler' 
              ]
  need_dob: [ 
              'registration-handler'
            ]
  force_admin:  [ 
                  '67gen',
                  'admin',
                  'compare',
                  'complice',
                  'noshow',
                  'pimp-my-faq',
                  'viewer'
                ]