main:
  tools:
    cm:
      name: 'Complice'
      description: "Generate competitors list with only useful information"
      folder: 'complice'
      locale: 'en'
    ge:
      name: '67Gen'
      description: 'Generate dual scorecards for 6x6/7x7 or 4bld/5bld when both events share the same cumulative'
      folder: '67gen'
      locale: 'en'
    ns:
      name: '(no)Show'
      description: 'Generate the list of no-shows for a competition after the competition ended'
      folder: 'noshow'
      locale: 'en'
    cp:
      name: 'COMPare'
      description: 'Compare registrants list between two competitions'
      folder: 'compare'
      locale: 'en'
    vw:
      name: 'Viewer'
      description: 'A simple viewer to display current competition information on projectors'
      folder: 'viewer'
      locale: 'en'
    co:
      name: 'Cumulo'
      description: 'Calculate remaining time compared to a cumulative'
      folder: 'cumulo'
      locale: 'en'
    do:
      name: 'DO Stats'
      description: 'Get your Delegate/organizer stats'
      folder: 'do-stats'
      locale: 'en'
    cu:
      name: 'Commande Utile'
      description: 'Permet la gestion de commandes pour les buvettes ou stands de compétitions francophones'
      folder: 'commande-utile'
      locale: 'fr'
    fq:
      name: 'Pimp My FAQ'
      description: "Génère la FAQ et les informations d'inscription pour les compétitions soutenues par l'AFS"
      folder: 'pimp-my-faq'
      locale: 'fr'
    rg:
      name: 'Registration Checker'
      description: "Gestion des rappels de confirmation d'inscription"
      folder: 'registration-checker'
      locale: 'fr'
    tt:
      name: 'TUTestes'
      description: "Session d'entraînement à la gestion des inscriptions"
      folder: 'tutestes'
      locale: 'fr'
  link: 
    en: 'click&nbsp;here'
    fr: 'clique&nbsp;ici'
